apiVersion: apps/v1
kind: Deployment
metadata:
  name: __NAME__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: __NAME__
  template:
    metadata:
      labels:
        app: __NAME__
    spec:
      containers:
        - name: frontend
          image: petlog/frontend:__IMAGE_TAG__
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/
            - name: tls-secret
              mountPath: /etc/nginx/
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: nginx-config
        - name: tls-secret
          secret:
            secretName: tls-secret
            items:
              - key: tls.crt
                path: certificates.crt
              - key: tls.key
                path: private.key
